services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Bridging\Service\CatalogingInterfacing\CatalogingCategoryApiClientBridge: ~

    App\Interfacing\ServiceInterface\Interfacing\CategoryApiClientInterface:
        alias: App\Bridging\Service\CatalogingInterfacing\CatalogingCategoryApiClientBridge
